# Generated by Django 4.1.1 on 2022-10-13 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("service", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="gender",
            field=models.CharField(default="", max_length=50),
        ),
    ]
