# Generated by Django 4.1.1 on 2022-10-14 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("service", "0002_user_gender"),
    ]

    operations = [
        migrations.CreateModel(
            name="BaseModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="College",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("collegeName", models.CharField(max_length=50)),
                ("collegeAddress", models.CharField(max_length=50)),
                ("collegeState", models.CharField(max_length=50)),
                ("collegeCity", models.CharField(max_length=20)),
                ("collegePhoneNumber", models.CharField(max_length=20)),
            ],
            options={"db_table": "SOS_COLLEGE",},
        ),
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("courseName", models.CharField(max_length=50)),
                ("courseDescription", models.CharField(max_length=100)),
                ("courseDuration", models.CharField(max_length=100)),
            ],
            options={"db_table": "SOS_COURSE",},
        ),
        migrations.CreateModel(
            name="Faculty",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("firstName", models.CharField(max_length=50)),
                ("lastName", models.CharField(max_length=50)),
                ("email", models.EmailField(max_length=254)),
                ("password", models.CharField(max_length=20)),
                ("address", models.CharField(max_length=50)),
                ("gender", models.CharField(max_length=50)),
                ("dob", models.DateField(max_length=20)),
                ("college_ID", models.IntegerField()),
                ("collegeName", models.CharField(max_length=50)),
                ("subject_ID", models.IntegerField()),
                ("subjectName", models.CharField(max_length=50)),
                ("course_ID", models.IntegerField()),
                ("courseName", models.CharField(max_length=50)),
            ],
            options={"db_table": "SOS_FACULTY",},
        ),
        migrations.CreateModel(
            name="Marksheet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("rollNumber", models.CharField(max_length=50)),
                ("name", models.CharField(max_length=50)),
                ("physics", models.IntegerField()),
                ("chemistry", models.IntegerField()),
                ("maths", models.IntegerField()),
            ],
            options={"db_table": "SOS_MARKSHEET",},
        ),
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("firstName", models.CharField(max_length=50)),
                ("lastName", models.CharField(max_length=50)),
                ("dob", models.DateField(max_length=20)),
                ("mobileNumber", models.CharField(max_length=20)),
                ("email", models.EmailField(max_length=254)),
                ("college_ID", models.IntegerField()),
                ("collegeName", models.CharField(max_length=50)),
            ],
            options={"db_table": "SOS_STUDENT",},
        ),
        migrations.CreateModel(
            name="Subject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("subjectName", models.CharField(max_length=50)),
                ("subjectDescription", models.CharField(max_length=50)),
                ("course_ID", models.IntegerField()),
                ("courseName", models.CharField(max_length=50)),
            ],
            options={"db_table": "SOS_SUBJECT",},
        ),
        migrations.CreateModel(
            name="TimeTable",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("examTime", models.CharField(max_length=40)),
                ("examDate", models.DateField()),
                ("subject_ID", models.IntegerField()),
                ("subjectName", models.CharField(max_length=50)),
                ("course_ID", models.IntegerField()),
                ("courseName", models.CharField(max_length=50)),
                ("semester", models.CharField(max_length=50)),
            ],
            options={"db_table": "SOS_TIMETABLE",},
        ),
    ]
